### ISSUE TITLE
pokt-index errors 'list' object has no attribute 'amount' 

### ISSUE THREAD

**Issue by ManInWeb3** [pokt-foundation/pypocket#2]
pokt-index errors `'list' object has no attribute 'amount'` and cannot download txs

My goal is to download transactions for a period to do some analytics.

I see the error on Linux and MacOS 

**To Reproduce**
Install with following steps from the readme.:
1. Run `pokt-index -j 2 -u https://mainnet.gateway.pokt.network/v1/lb/__APPID__`
2. See the following error:
```
Error encountered during: 1 - 250
'list' object has no attribute 'amount'
Error encountered during: 501 - 750
'list' object has no attribute 'amount'
Error encountered during: 751 - 1000
'list' object has no attribute 'amount'
...
```

**Expected behavior**
To get transactions downloaded

**Screenshots**

**Linux:**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
$ python3 --version
Python 3.9.2
```

**MacOS**
MacOS 12.4
python version 3.9.13
![image](https://user-images.githubusercontent.com/16667906/179630680-96c7bdbd-6375-4481-8d80-06fad36cc822.png)

**Comment by blockjoe** [comment]
Pushed out the fix for this on 76d4b4e309030fc7f143ab5d2c02c7bf44ea6419.
